---
# GitHub issue form syntax.
name: 🪲 [Bug]
description: Submit a bug report
title: '🪲[Bug]: '
labels: ['bug', 'triage']
# GitHub issue form schema.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide
        as much information as possible so we can help you quickly.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: >-
        A clear and concise description of what the bug is vs. what you expected
        to happen.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        What version, commit, platform, or configuration were you using when
        the problem occurred?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        List the steps, commands, inputs, or conditions that reproduce the
        problem.
    validations:
      required: true
  - type: textarea
    id: relevant-details
    attributes:
      label: Relevant details
      description: >-
        Share any relevant code, configuration, logs, screenshots, links, or
        other context.
  - type: textarea
    id: supporting-evidence
    attributes:
      label: Supporting evidence
      description: |
        Include error messages, logs, screenshots, links, or other evidence
        that helps explain the problem.
