---
# GitHub issue form syntax.
name: 🌞 [Other]
description: Submit an issue with any other topic
title: '🌞 [Other]: '
labels: ['triage']
# GitHub issue form schema.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form! Please provide as much
        information as possible so we can help you quickly.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description.
    validations:
      required: true
